## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/itpackaging
    # platform: postgres
    # initialization-mode: always
    #continue-on-error: true
  jpa:
    jpa:
      hibernate.ddl-auto: update
      generate-ddl: true
      show-sql: true
    #show-sql: false
    #    generate-ddl: false
    #  hibernate:
    #     ddl-auto: update
    #  database: postgresql
    #   properties:
    #     hibernate:
    #      temp:
    #       use_jdbc_metadata_defaults: false;
    # database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  #      dialect: org.hibernate.dialect.MySQL5Dialect

  #  jackson:
  #    default-property-inclusion: non_null
  #  redis:
  #    host: localhost
  #    port: 6379
  #  freemarker:
  #      cache: false




  queries:
    users-query: select email, password, active from users where email=?
    roles-query: select email, role from users where email=?
server:
  servlet:
    contextPath: /api

jwtSecret: me.zhulin
jwtExpiration: 86400
